mattermost:
  client:
    apiurl: "MATTERMOST_HOST"
    hook: "MATTERMOST_HOOK"

giphy:
  client:
    apiurl: "https://api.giphy.com/"
    apikey: "GIPHY_API_KEY"

urbandictionary:
  client:
    apiurl: "https://api.urbandictionary.com"